### PR TITLE
Fixes #1 and #2, Dockerfiles update

### LINKED ISSUE #1: Docker build fails with unexpected status code for CentOS
Problem
---------

```
$  docker build -t pind-centos - < Dockerfile.centos
[+] Building 1.0s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                                                   0.0s
 => => transferring dockerfile: 544B                                                                                                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                                                                                        0.0s
 => ERROR [internal] load metadata for registry.centos.org/centos8:latest                                                                                                                                                              0.9s
------
 > [internal] load metadata for registry.centos.org/centos8:latest:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: unexpected status code [manifests latest]: 403 Forbidden
```

Workaround
----------------
```
$ docker pull registry.centos.org/centos:latest
latest: Pulling from centos
926a85fb4806: Pull complete
Digest: sha256:1087af8d5c16af90d455ced5b1fd76a46150ac2b1922bdd41552391365f7e4fe
Status: Downloaded newer image for registry.centos.org/centos:latest
registry.centos.org/centos:latest
$ docker build -t pind-centos - < Dockerfile.centos
[+] Building 59.1s (6/6) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                                                   0.0s
 => => transferring dockerfile: 543B                                                                                                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                                                                                        0.0s
 => [internal] load metadata for registry.centos.org/centos:latest                                                                                                                                                                     0.0s
 => [1/2] FROM registry.centos.org/centos:latest                                                                                                                                                                                       0.0s
 => => resolve registry.centos.org/centos:latest                                                                                                                                                                                       0.0s
 => [2/2] RUN dnf install -y podman crun &&     cp /usr/share/containers/containers.conf /etc/containers/containers.conf &&     sed -i '/^# cgroup_manager = "systemd"/ a cgroup_manager = "cgroupfs"' /etc/containers/containers.co  57.4s
 => exporting to image                                                                                                                                                                                                                 1.6s
 => => exporting layers                                                                                                                                                                                                                1.6s
 => => writing image sha256:ee6ea4bd45fb0ea6c6d537e498c43fa4f251cd91c4841c14034c101703fea3cb                                                                                                                                           0.0s
 => => naming to docker.io/library/pind-centos
```

which avoids to check the registry for the existence of the container

### PR DESCRIPTION
**Pull request by srbala**
Doing container update and leaving the events reports to file resolves your issue. `podman` version is updated to `3.0.x`, since they are avaiable.

PR  Fixes #1 and #2

### CODE REVIEW

**Comment by srbala** [comment]
Here in `podman` dind deaitls, `version`, `info`, running `centos` and `alpine`

```log
sh-4.4# podman version
Version:      3.0.2-dev
API Version:  3.0.0
Go Version:   go1.16.1
Built:        Thu May 20 16:22:46 2021
OS/Arch:      linux/amd64
```

```log
sh-4.4# podman info
host:
  arch: amd64
  buildahVersion: 1.19.8
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.26-1.module_el8.4.0+781+acf4c33b.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: 76c72c12c83408e6ddaaa7bcd25e96ca20bf9348'
  cpus: 7
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: cf1cac941d82
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.25-linuxkit
  linkmode: dynamic
  memFree: 2395090944
  memTotal: 12563709952
  ociRuntime:
    name: runc
    package: runc-1.0.0-70.rc92.module_el8.4.0+673+eabfc99d.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 1073737728
  swapTotal: 1073737728
  uptime: 38h 4m 7.33s (Approximately 1.58 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus: {}
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1621527766
  BuiltTime: Thu May 20 16:22:46 2021
  GitCommit: ""
  GoVersion: go1.16.1
  OsArch: linux/amd64
  Version: 3.0.2-dev
```

```log
sh-4.4# podman run --rm -it registry.centos.org/centos:latest bash
Trying to pull registry.centos.org/centos:latest...
Getting image source signatures
Copying blob 926a85fb4806 done  
Copying config 2f3766df23 done  
Writing manifest to image destination
Storing signatures
[root@f7ce0e70836b /]# 
```

```log
sh-4.4# podman run --rm -it docker.io/alpine:latest echo "Hello from Alpine inside Podman"
Trying to pull docker.io/library/alpine:latest...
Getting image source signatures
Copying blob 540db60ca938 done  
Copying config 6dbb9cc540 done  
Writing manifest to image destination
Storing signatures
Hello from Alpine inside Podman
sh-4.4# 
```

**Comment by srbala** [comment]
@gbraad are you able to check this PR

**Comment by gbraad** [comment]
@srbala having to run update in the image usually indicates that the upstream/provided images are old. I'll also check with them, but merging.

**Comment by gbraad** [comment]
Thanks 👍

**Comment by srbala** [comment]
> @srbala having to run update in the image usually indicates that the upstream/provided images are old. I'll also check with them, but merging.
@gbraad agreed, it has been months centos has been updated. You may need to look for new kids in the block, `almalinux` or `rockylinux` for `RHEL 8.4` series release. Another alternative would be using `UBI` or `UBI-minimal`.

**Comment by gbraad** [comment]
Will discuss with the guys what they suggest.the UBI is not my preferred option, but neither Rocky or Alma. If there won't tbe a Stream option I rather drop the image entirely.

**Pull request merged**
